#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Conscript
export CONSCRIPT_HOME="$HOME/.conscript"
export CONSCRIPT_OPTS="-XX:MaxPermSize=512M -Dfile.encoding=UTF-8"

# General path setup
path=(
  "$HOME/bin" 
  "$HOME/.cabal/bin" 
  "$HOME/.local/bin"  
  "$HOME/.rvm/bin"
  "$CONSCRIPT_HOME/bin"
  $path
)

# "What was that alias again?"
function agrep {
  alias | grep $*
}
