#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Conscript
export CONSCRIPT_HOME="$HOME/.conscript"
export CONSCRIPT_OPTS="-XX:MaxPermSize=512M -Dfile.encoding=UTF-8"

# General path setup
path=(
  "/usr/local/bin"
  "$HOME/bin" 
  "$HOME/.cabal/bin" 
  "$HOME/.local/bin"  
  "$HOME/.rvm/bin"
  "$CONSCRIPT_HOME/bin"
  "$HOME/Library/Python/2.7/bin"
  $path
)

export EDITOR=vim

# iTerm2
if [ -e ~/.iterm2_shell_integration.zsh ]; then
  source ~/.iterm2_shell_integration.zsh
fi

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Powerline
if [ -f "$(which powerline-daemon)" ]; then
  powerline-daemon -q
  source "$HOME/Library/Python/2.7/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh"
fi

# If `hub` is installed, alias it
if [ -f "$(which hub)" ]; then
  eval "$(hub alias -s)"
fi

## Aliases

# Print whatever's in the pasteboard expanding escape codes.
# Useful for making stack traces from JSON-encoded logs readable.
alias pbprintf='printf "$(pbp)"'

# I don't like the prezto super-safe rm
if alias rm >&-; then
  unalias rm
fi

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# virtualenv
if [ -e $(which virtualenv) ]; then
  source "$HOME/Library/Python/2.7/bin/virtualenvwrapper.sh"
fi

# Local overrides
if [ -e ~/.zlocal ]; then
  source ~/.zlocal
fi
